Exception HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f0496cc3530>: Failed to resolve 'metadata.google.internal' ([Errno -2] Name or service not known)")) occured attempting gce_instance resource detection
--2025-10-03 18:23:29--  http://127.0.0.1:12345/
Connecting to 127.0.0.1:12345... connected.
HTTP request sent, awaiting response... 418 I'm a teapot
2025-10-03 18:23:30 ERROR 418: I'm a teapot.

